{"name": "test_correct_login", "status": "broken", "statusDetails": {"message": "_pytest.fixtures.FixtureLookupError: ('self', <FixtureRequest for <Function test_correct_login>>)", "trace": "file C:\\Users\\User\\PycharmProjects\\shop_tests_allure\\tests\\login_form\\test_login_form.py, line 21\n  @allure.description(\"Login with correct login\")\n  @allure.severity(severity_level=\"NORMAL\")\n  def test_correct_login(self):\nE       fixture 'self' not found\n>       available fixtures: cache, capfd, capfdbinary, caplog, capsys, capsysbinary, doctest_namespace, monkeypatch, pytestconfig, record_property, record_testsuite_property, record_xml_attribute, recwarn, set_up, tmp_path, tmp_path_factory, tmpdir, tmpdir_factory\n>       use 'pytest --fixtures [testpath]' for help on them.\n\nC:\\Users\\User\\PycharmProjects\\shop_tests_allure\\tests\\login_form\\test_login_form.py:21"}, "description": "Login with correct login", "start": 1615729404649, "stop": 1615729404649, "uuid": "c68eefae-a001-4c41-a43b-5ed722322a7a", "historyId": "698274acd40a46a567a1c85de1226539", "testCaseId": "2d4a06c4466c00eec654008db72756b7", "fullName": "test_login_form#test_correct_login", "labels": [{"name": "severity", "value": "NORMAL"}, {"name": "suite", "value": "test_login_form"}, {"name": "host", "value": "User-ПК"}, {"name": "thread", "value": "7196-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "test_login_form"}]}